repos:
  # General formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Remove trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # Ensure files end with exactly one newline
      - id: end-of-file-fixer
      # Check for large files
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      # Check YAML syntax
      - id: check-yaml
      # Check JSON syntax
      - id: check-json
      # Check for merge conflicts
      - id: check-merge-conflict
      # Mixed line endings
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # C/C++ formatting with clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: \.(c|h|cpp|hpp|cc|cxx)$
        args: ["-i"]

  # Rust formatting
  - repo: local
    hooks:
      - id: rust-fmt
        name: rust fmt
        entry: bash -c 'for file in "$@"; do (cd "$(dirname "$file")" && cargo fmt); done'
        language: system
        files: \.rs$
        pass_filenames: true

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: \.py$

  # Nix formatting
  - repo: https://github.com/NixOS/nixfmt
    rev: v1.0.0
    hooks:
      - id: nixfmt
        files: \.nix$

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|json|yaml|yml|md)$
        exclude: flake\.lock$
